// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control_service.proto

package polardb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InsSpec struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Instype              string   `protobuf:"bytes,6,opt,name=instype,proto3" json:"instype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsSpec) Reset()         { *m = InsSpec{} }
func (m *InsSpec) String() string { return proto.CompactTextString(m) }
func (*InsSpec) ProtoMessage()    {}
func (*InsSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b494b2e1086331d0, []int{0}
}
func (m *InsSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsSpec.Unmarshal(m, b)
}
func (m *InsSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsSpec.Marshal(b, m, deterministic)
}
func (dst *InsSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsSpec.Merge(dst, src)
}
func (m *InsSpec) XXX_Size() int {
	return xxx_messageInfo_InsSpec.Size(m)
}
func (m *InsSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_InsSpec.DiscardUnknown(m)
}

var xxx_messageInfo_InsSpec proto.InternalMessageInfo

func (m *InsSpec) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *InsSpec) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InsSpec) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InsSpec) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InsSpec) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *InsSpec) GetInstype() string {
	if m != nil {
		return m.Instype
	}
	return ""
}

type SyncInstanceRequest struct {
	SystemIdentify       string   `protobuf:"bytes,1,opt,name=system_identify,json=systemIdentify,proto3" json:"system_identify,omitempty"`
	Ins                  *InsSpec `protobuf:"bytes,2,opt,name=ins,proto3" json:"ins,omitempty"`
	Rw                   *InsSpec `protobuf:"bytes,3,opt,name=rw,proto3" json:"rw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstanceRequest) Reset()         { *m = SyncInstanceRequest{} }
func (m *SyncInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*SyncInstanceRequest) ProtoMessage()    {}
func (*SyncInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b494b2e1086331d0, []int{1}
}
func (m *SyncInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstanceRequest.Unmarshal(m, b)
}
func (m *SyncInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstanceRequest.Marshal(b, m, deterministic)
}
func (dst *SyncInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstanceRequest.Merge(dst, src)
}
func (m *SyncInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_SyncInstanceRequest.Size(m)
}
func (m *SyncInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstanceRequest proto.InternalMessageInfo

func (m *SyncInstanceRequest) GetSystemIdentify() string {
	if m != nil {
		return m.SystemIdentify
	}
	return ""
}

func (m *SyncInstanceRequest) GetIns() *InsSpec {
	if m != nil {
		return m.Ins
	}
	return nil
}

func (m *SyncInstanceRequest) GetRw() *InsSpec {
	if m != nil {
		return m.Rw
	}
	return nil
}

type SyncInstanceResponse struct {
	// 返回码
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstanceResponse) Reset()         { *m = SyncInstanceResponse{} }
func (m *SyncInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*SyncInstanceResponse) ProtoMessage()    {}
func (*SyncInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b494b2e1086331d0, []int{2}
}
func (m *SyncInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstanceResponse.Unmarshal(m, b)
}
func (m *SyncInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstanceResponse.Marshal(b, m, deterministic)
}
func (dst *SyncInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstanceResponse.Merge(dst, src)
}
func (m *SyncInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_SyncInstanceResponse.Size(m)
}
func (m *SyncInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstanceResponse proto.InternalMessageInfo

func (m *SyncInstanceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SyncInstanceResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*InsSpec)(nil), "polardb.InsSpec")
	proto.RegisterType((*SyncInstanceRequest)(nil), "polardb.SyncInstanceRequest")
	proto.RegisterType((*SyncInstanceResponse)(nil), "polardb.SyncInstanceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlServiceClient interface {
	// 下发实例元信息(有密码敏感信息，UE不存储实例元信息，UE进程重启后丢失实例信息，需要CM一直下发实例元信息，类型心跳机制)
	SyncInstance(ctx context.Context, in *SyncInstanceRequest, opts ...grpc.CallOption) (*SyncInstanceResponse, error)
}

type controlServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlServiceClient(cc *grpc.ClientConn) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) SyncInstance(ctx context.Context, in *SyncInstanceRequest, opts ...grpc.CallOption) (*SyncInstanceResponse, error) {
	out := new(SyncInstanceResponse)
	err := c.cc.Invoke(ctx, "/polardb.ControlService/SyncInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
type ControlServiceServer interface {
	// 下发实例元信息(有密码敏感信息，UE不存储实例元信息，UE进程重启后丢失实例信息，需要CM一直下发实例元信息，类型心跳机制)
	SyncInstance(context.Context, *SyncInstanceRequest) (*SyncInstanceResponse, error)
}

func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}

func _ControlService_SyncInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SyncInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/polardb.ControlService/SyncInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SyncInstance(ctx, req.(*SyncInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "polardb.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncInstance",
			Handler:    _ControlService_SyncInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control_service.proto",
}

func init() { proto.RegisterFile("control_service.proto", fileDescriptor_b494b2e1086331d0) }

var fileDescriptor_b494b2e1086331d0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0xfe, 0xb5, 0xa3, 0xd4, 0x12, 0x15, 0x42, 0x51, 0x28, 0x7b, 0xb1, 0xa7, 0x1e,
	0xea, 0xd5, 0x9b, 0xa7, 0xe2, 0x2d, 0x3d, 0x4b, 0x49, 0xb3, 0xa3, 0x2e, 0xb4, 0x49, 0xcc, 0xa4,
	0x2e, 0x7b, 0xf7, 0x7b, 0xf8, 0x55, 0x25, 0xc9, 0x6e, 0x51, 0xa8, 0xb7, 0xf7, 0xe6, 0x37, 0x64,
	0xe6, 0x65, 0xe0, 0x46, 0x19, 0xed, 0x9d, 0xd9, 0x6d, 0x08, 0xdd, 0x67, 0xa9, 0x70, 0x61, 0x9d,
	0xf1, 0x86, 0x0d, 0xad, 0xd9, 0x49, 0x57, 0x6c, 0xf3, 0xef, 0x0c, 0x86, 0x2b, 0x4d, 0x6b, 0x8b,
	0x8a, 0x31, 0xe8, 0xbd, 0x1b, 0xf2, 0x3c, 0x9b, 0x65, 0xf3, 0x91, 0x88, 0x3a, 0xd4, 0xac, 0x71,
	0x9e, 0x77, 0x66, 0xd9, 0xbc, 0x2f, 0xa2, 0x66, 0x53, 0x38, 0x3b, 0x10, 0x3a, 0x2d, 0xf7, 0xc8,
	0xbb, 0xb1, 0xf7, 0xe8, 0x03, 0xb3, 0x92, 0xa8, 0x32, 0xae, 0xe0, 0xbd, 0xc4, 0x5a, 0x1f, 0x58,
	0x21, 0xbd, 0xdc, 0x4a, 0x42, 0xde, 0x4f, 0xac, 0xf5, 0x8c, 0xc3, 0xb0, 0xd4, 0xe4, 0x6b, 0x8b,
	0x7c, 0x10, 0x51, 0x6b, 0xf3, 0xaf, 0x0c, 0xae, 0xd6, 0xb5, 0x56, 0x2b, 0x4d, 0x5e, 0x6a, 0x85,
	0x02, 0x3f, 0x0e, 0x48, 0x9e, 0xdd, 0xc3, 0x25, 0xd5, 0xe4, 0x71, 0xbf, 0x29, 0x0b, 0xd4, 0xbe,
	0x7c, 0xad, 0x9b, 0xc5, 0xc7, 0xa9, 0xbc, 0x6a, 0xaa, 0x2c, 0x87, 0x6e, 0xa9, 0x29, 0x26, 0x38,
	0x5f, 0x4e, 0x16, 0x4d, 0xf2, 0x45, 0x93, 0x5a, 0x04, 0xc8, 0x66, 0xd0, 0x71, 0x55, 0x0c, 0x73,
	0xaa, 0xa5, 0xe3, 0xaa, 0xfc, 0x11, 0xae, 0xff, 0x6e, 0x41, 0xd6, 0x68, 0xc2, 0xf0, 0x41, 0xca,
	0x14, 0x18, 0x67, 0xf7, 0x45, 0xd4, 0x6c, 0x02, 0xdd, 0x3d, 0xbd, 0xc5, 0x89, 0x23, 0x11, 0xe4,
	0xf2, 0x05, 0xc6, 0x4f, 0xe9, 0x10, 0xeb, 0x74, 0x07, 0xf6, 0x0c, 0x17, 0xbf, 0xdf, 0x63, 0xb7,
	0xc7, 0xa9, 0x27, 0xc2, 0x4e, 0xef, 0xfe, 0xa1, 0x69, 0x89, 0xed, 0x20, 0x5e, 0xf5, 0xe1, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x60, 0x14, 0x5b, 0x26, 0xee, 0x01, 0x00, 0x00,
}
